//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace WinForms.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resources_hr {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_hr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("WinForms.Resources.Resources", typeof(Resources_hr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prekinuto.
        /// </summary>
        public static string Aborted {
            get {
                return ResourceManager.GetString("Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj u favorite.
        /// </summary>
        public static string AddFavorite {
            get {
                return ResourceManager.GetString("AddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dogodila se greška pri dohvacanju .
        /// </summary>
        public static string AnErrorOccurredWhileFetchingTeamsExMessage {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileFetchingTeamsExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dogodila se greška pri dohvacanju.
        /// </summary>
        public static string AnErrorOccurredWhileLoadingMatchesExMessage {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileLoadingMatchesExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posječenost.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapetan.
        /// </summary>
        public static string Captain {
            get {
                return ResourceManager.GetString("Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartoni:.
        /// </summary>
        public static string cards {
            get {
                return ResourceManager.GetString("cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promjena jezika.
        /// </summary>
        public static string changingLangtoEnglish {
            get {
                return ResourceManager.GetString("changingLangtoEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hr.
        /// </summary>
        public static string Croatian {
            get {
                return ResourceManager.GetString("Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li sigurni ?.
        /// </summary>
        public static string exitConfirmationBody {
            get {
                return ResourceManager.GetString("exitConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izlaz iz aplikacije.
        /// </summary>
        public static string exitConfirmationTitle {
            get {
                return ResourceManager.GetString("exitConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoritt.
        /// </summary>
        public static string FavoritePlayerItem {
            get {
                return ResourceManager.GetString("FavoritePlayerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žene.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dohvačam.
        /// </summary>
        public static string Fetching {
            get {
                return ResourceManager.GetString("Fetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golovi:.
        /// </summary>
        public static string goals {
            get {
                return ResourceManager.GetString("goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li sigurni da želite promjeniti jezik?.
        /// </summary>
        public static string languageChangeBody {
            get {
                return ResourceManager.GetString("languageChangeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promjena Jezika.
        /// </summary>
        public static string languageChangeTittle {
            get {
                return ResourceManager.GetString("languageChangeTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitaj sliku.
        /// </summary>
        public static string LoadImage {
            get {
                return ResourceManager.GetString("LoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loadImageItem.
        /// </summary>
        public static string LoadImageItemName {
            get {
                return ResourceManager.GetString("LoadImageItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muški.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rangiranje po kartonima.
        /// </summary>
        public static string rankingsCards {
            get {
                return ResourceManager.GetString("rankingsCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rangiranje po golovima.
        /// </summary>
        public static string rankingsGoals {
            get {
                return ResourceManager.GetString("rankingsGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makni Favorita.
        /// </summary>
        public static string RemoveFavorite {
            get {
                return ResourceManager.GetString("RemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Type: $&quot;{selectedType}&quot; Selected Language: $&quot;{selectedLanguage}&quot;.
        /// </summary>
        public static string SettingsChosenWindow {
            get {
                return ResourceManager.GetString("SettingsChosenWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi Odabir.
        /// </summary>
        public static string SettingsConfirmationBody {
            get {
                return ResourceManager.GetString("SettingsConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcije.
        /// </summary>
        public static string SettingsConfirmationTitle {
            get {
                return ResourceManager.GetString("SettingsConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi tim.
        /// </summary>
        public static string teamSelect {
            get {
                return ResourceManager.GetString("teamSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi promjenu tima.
        /// </summary>
        public static string teamSelectionBody {
            get {
                return ResourceManager.GetString("teamSelectionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promjena tima.
        /// </summary>
        public static string teamSelectionTitle {
            get {
                return ResourceManager.GetString("teamSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timovi su uspješno učitani.
        /// </summary>
        public static string TeamsSuccessfullyLoaded {
            get {
                return ResourceManager.GetString("TeamsSuccessfullyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi promjenu tipa .
        /// </summary>
        public static string typeChangeBody {
            get {
                return ResourceManager.GetString("typeChangeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promjena Tipa.
        /// </summary>
        public static string typeChangeTitle {
            get {
                return ResourceManager.GetString("typeChangeTitle", resourceCulture);
            }
        }
    }
}
