//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinForms.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a picture.
        /// </summary>
        public static string _openFileDialog_Title {
            get {
                return ResourceManager.GetString("_openFileDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        public static string Aborted {
            get {
                return ResourceManager.GetString("Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorite.
        /// </summary>
        public static string AddFavorite {
            get {
                return ResourceManager.GetString("AddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while fetching teams.
        /// </summary>
        public static string AnErrorOccurredWhileFetchingTeamsExMessage {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileFetchingTeamsExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading matches: {ex.Message}.
        /// </summary>
        public static string AnErrorOccurredWhileLoadingMatchesExMessage {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileLoadingMatchesExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        public static string Captain {
            get {
                return ResourceManager.GetString("Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards:.
        /// </summary>
        public static string cards {
            get {
                return ResourceManager.GetString("cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Change.
        /// </summary>
        public static string changingLangtoEnglish {
            get {
                return ResourceManager.GetString("changingLangtoEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hr.
        /// </summary>
        public static string Croatian {
            get {
                return ResourceManager.GetString("Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string exitConfirmationBody {
            get {
                return ResourceManager.GetString("exitConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application closing.
        /// </summary>
        public static string exitConfirmationTitle {
            get {
                return ResourceManager.GetString("exitConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favoritePlayerItem.
        /// </summary>
        public static string FavoritePlayerItem {
            get {
                return ResourceManager.GetString("FavoritePlayerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching.
        /// </summary>
        public static string Fetching {
            get {
                return ResourceManager.GetString("Fetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals:.
        /// </summary>
        public static string goals {
            get {
                return ResourceManager.GetString("goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files (*.bmp;*.jpg;*.jpeg;*.png)|*.bmp;*.jpg;*.jpeg;*.png.
        /// </summary>
        public static string Imagesfilter {
            get {
                return ResourceManager.GetString("Imagesfilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you certain you want to the change the Language?.
        /// </summary>
        public static string languageChangeBody {
            get {
                return ResourceManager.GetString("languageChangeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Change.
        /// </summary>
        public static string languageChangeTittle {
            get {
                return ResourceManager.GetString("languageChangeTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In attendance:.
        /// </summary>
        public static string lblAttendance_Text {
            get {
                return ResourceManager.GetString("lblAttendance.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away Team:.
        /// </summary>
        public static string lblAwayTeam_Text {
            get {
                return ResourceManager.GetString("lblAwayTeam.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Team:.
        /// </summary>
        public static string lblHomeTeam_Text {
            get {
                return ResourceManager.GetString("lblHomeTeam.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string lblLocation_Text {
            get {
                return ResourceManager.GetString("lblLocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Image.
        /// </summary>
        public static string LoadImage {
            get {
                return ResourceManager.GetString("LoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loadImageItem.
        /// </summary>
        public static string LoadImageItemName {
            get {
                return ResourceManager.GetString("LoadImageItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football Tournament.
        /// </summary>
        public static string MainFormName {
            get {
                return ResourceManager.GetString("MainFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking by cards.
        /// </summary>
        public static string rankingsCards {
            get {
                return ResourceManager.GetString("rankingsCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rankings by goals.
        /// </summary>
        public static string rankingsGoals {
            get {
                return ResourceManager.GetString("rankingsGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Favorite.
        /// </summary>
        public static string RemoveFavorite {
            get {
                return ResourceManager.GetString("RemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Type: $&quot;{selectedType}&quot; Selected Language: $&quot;{selectedLanguage}&quot;.
        /// </summary>
        public static string SettingsChosenWindow {
            get {
                return ResourceManager.GetString("SettingsChosenWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm selection!.
        /// </summary>
        public static string SettingsConfirmationBody {
            get {
                return ResourceManager.GetString("SettingsConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsConfirmationTitle {
            get {
                return ResourceManager.GetString("SettingsConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a team.
        /// </summary>
        public static string teamSelect {
            get {
                return ResourceManager.GetString("teamSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm team Change.
        /// </summary>
        public static string teamSelectionBody {
            get {
                return ResourceManager.GetString("teamSelectionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Team.
        /// </summary>
        public static string teamSelectionTitle {
            get {
                return ResourceManager.GetString("teamSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams successfully loaded.
        /// </summary>
        public static string TeamsSuccessfullyLoaded {
            get {
                return ResourceManager.GetString("TeamsSuccessfullyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm tournament type change.
        /// </summary>
        public static string typeChangeBody {
            get {
                return ResourceManager.GetString("typeChangeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Change.
        /// </summary>
        public static string typeChangeTitle {
            get {
                return ResourceManager.GetString("typeChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string typeFemale {
            get {
                return ResourceManager.GetString("typeFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string typeMale {
            get {
                return ResourceManager.GetString("typeMale", resourceCulture);
            }
        }
    }
}
