//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Captain.
        /// </summary>
        public static string _Captian {
            get {
                return ResourceManager.GetString("_Captian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals Scored: .
        /// </summary>
        public static string _goalsScored {
            get {
                return ResourceManager.GetString("_goalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a team captain.
        /// </summary>
        public static string _NotCaptian {
            get {
                return ResourceManager.GetString("_NotCaptian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name: .
        /// </summary>
        public static string _playerName {
            get {
                return ResourceManager.GetString("_playerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: .
        /// </summary>
        public static string _playerPoisition {
            get {
                return ResourceManager.GetString("_playerPoisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt Number: .
        /// </summary>
        public static string _playerShirtNumber {
            get {
                return ResourceManager.GetString("_playerShirtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Cards received:.
        /// </summary>
        public static string _YellowCards {
            get {
                return ResourceManager.GetString("_YellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Size.
        /// </summary>
        public static string appSize {
            get {
                return ResourceManager.GetString("appSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string appSizeFullScreen {
            get {
                return ResourceManager.GetString("appSizeFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string appSizeLarge {
            get {
                return ResourceManager.GetString("appSizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string appSizeMedium {
            get {
                return ResourceManager.GetString("appSizeMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string appSizeSmall {
            get {
                return ResourceManager.GetString("appSizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statistics.
        /// </summary>
        public static string btnAwayTeamInformation {
            get {
                return ResourceManager.GetString("btnAwayTeamInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statistics.
        /// </summary>
        public static string btnHomeTeamInformation {
            get {
                return ResourceManager.GetString("btnHomeTeamInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string btnSaveSettings {
            get {
                return ResourceManager.GetString("btnSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string btnSettingsSave {
            get {
                return ResourceManager.GetString("btnSettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Fetching Data.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa Code:.
        /// </summary>
        public static string FifaCode {
            get {
                return ResourceManager.GetString("FifaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Football_Field {
            get {
                object obj = ResourceManager.GetObject("Football_Field", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Football_Pitch {
            get {
                object obj = ResourceManager.GetObject("Football_Pitch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string genderSelectFemale {
            get {
                return ResourceManager.GetString("genderSelectFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string genderSelectMale {
            get {
                return ResourceManager.GetString("genderSelectMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals Received:.
        /// </summary>
        public static string GoalsReceived {
            get {
                return ResourceManager.GetString("GoalsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals Scored:.
        /// </summary>
        public static string GoalsScored {
            get {
                return ResourceManager.GetString("GoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string languageSelectCroatian {
            get {
                return ResourceManager.GetString("languageSelectCroatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string languageSelectEnglish {
            get {
                return ResourceManager.GetString("languageSelectEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure ?.
        /// </summary>
        public static string mainFormClosingBody {
            get {
                return ResourceManager.GetString("mainFormClosingBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Form Closing.
        /// </summary>
        public static string mainFormClosingTitle {
            get {
                return ResourceManager.GetString("mainFormClosingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football match.
        /// </summary>
        public static string mainFormTitle {
            get {
                return ResourceManager.GetString("mainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches ended in a draw:.
        /// </summary>
        public static string MatchesDraw {
            get {
                return ResourceManager.GetString("MatchesDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches Lost:.
        /// </summary>
        public static string MatchesLost {
            get {
                return ResourceManager.GetString("MatchesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches Played:.
        /// </summary>
        public static string MatchesPlayed {
            get {
                return ResourceManager.GetString("MatchesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches Won:.
        /// </summary>
        public static string MatchesWOn {
            get {
                return ResourceManager.GetString("MatchesWOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap placeholder_img {
            get {
                object obj = ResourceManager.GetObject("placeholder_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player information.
        /// </summary>
        public static string PlayerInformationTittle {
            get {
                return ResourceManager.GetString("PlayerInformationTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Away Team.
        /// </summary>
        public static string selectAwayTeam {
            get {
                return ResourceManager.GetString("selectAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Home Team.
        /// </summary>
        public static string selectHomeTeam {
            get {
                return ResourceManager.GetString("selectHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an away team.
        /// </summary>
        public static string SelectOpponent {
            get {
                return ResourceManager.GetString("SelectOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressing OK will close the settings.
        ///Warning: Chosen settings will not save this way..
        /// </summary>
        public static string settingsClosingBody {
            get {
                return ResourceManager.GetString("settingsClosingBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings closing.
        /// </summary>
        public static string settingsClosingTitle {
            get {
                return ResourceManager.GetString("settingsClosingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settingsMsgBoxCaption {
            get {
                return ResourceManager.GetString("settingsMsgBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed with choosen settings ?.
        /// </summary>
        public static string settingsMsgBoxText {
            get {
                return ResourceManager.GetString("settingsMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressing okay will close the current application and open settings..
        /// </summary>
        public static string SettingsOpeningBody {
            get {
                return ResourceManager.GetString("SettingsOpeningBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings opening.
        /// </summary>
        public static string SettingsOpeningTitle {
            get {
                return ResourceManager.GetString("SettingsOpeningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settingsTittle {
            get {
                return ResourceManager.GetString("settingsTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name:.
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Statistics.
        /// </summary>
        public static string TeamStatisticsInformationTittle {
            get {
                return ResourceManager.GetString("TeamStatisticsInformationTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string tournamentType {
            get {
                return ResourceManager.GetString("tournamentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressing OK will open WinForms application and close the current one..
        /// </summary>
        public static string WinFormsOpeningBody {
            get {
                return ResourceManager.GetString("WinFormsOpeningBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinForms Application Opening.
        /// </summary>
        public static string WinFormsOpeningTitle {
            get {
                return ResourceManager.GetString("WinFormsOpeningTitle", resourceCulture);
            }
        }
    }
}
